/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetByUsername } from "../../funcs/usersGetByUsername.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetUserByNameRequest$inboundSchema,
};

export const tool$usersGetByUsername: ToolDefinition<typeof args> = {
  name: "users-get-by-username",
  description: `Get user by user name`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersGetByUsername(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
