// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"context"
	"net/http"

	"mockserver/internal/logging"
)

// GeneratedHandlers returns all generated handlers.
func GeneratedHandlers(ctx context.Context, dir *logging.HTTPFileDirectory) []*GeneratedHandler {
	return []*GeneratedHandler{
		NewGeneratedHandler(ctx, dir, http.MethodPut, "/pet", "updatePet", opUpdatePet()),
		NewGeneratedHandler(ctx, dir, http.MethodPost, "/pet", "addPet", opAddPet()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/pet/findByStatus", "findPetsByStatus", opFindPetsByStatus()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/pet/findByTags", "findPetsByTags", opFindPetsByTags()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/pet/{petId}", "getPetById", opGetPetByID()),
		NewGeneratedHandler(ctx, dir, http.MethodDelete, "/pet/{petId}", "deletePet", opDeletePet()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/store/inventory", "getInventory", opGetInventory()),
		NewGeneratedHandler(ctx, dir, http.MethodPost, "/store/order", "placeOrder", opPlaceOrder()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/store/order/{orderId}", "getOrderById", opGetOrderByID()),
		NewGeneratedHandler(ctx, dir, http.MethodDelete, "/store/order/{orderId}", "deleteOrder", opDeleteOrder()),
		NewGeneratedHandler(ctx, dir, http.MethodPost, "/user", "createUser", opCreateUser()),
		NewGeneratedHandler(ctx, dir, http.MethodPost, "/user/createWithList", "createUsersWithListInput", opCreateUsersWithListInput()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/user/login", "loginUser", opLoginUser()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/user/logout", "logoutUser", opLogoutUser()),
		NewGeneratedHandler(ctx, dir, http.MethodGet, "/user/{username}", "getUserByName", opGetUserByName()),
		NewGeneratedHandler(ctx, dir, http.MethodPut, "/user/{username}", "updateUser", opUpdateUser()),
		NewGeneratedHandler(ctx, dir, http.MethodDelete, "/user/{username}", "deleteUser", opDeleteUser()),
	}
}
