// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"context"
	"mockserver/internal/logging"
	"net/http"
)

// GeneratedHandler is the type that encapsulates a generated handler.
type GeneratedHandler struct {
	// HTTP request handler function.
	handlerFunc http.HandlerFunc

	// Directory for raw HTTP request and response files.
	httpFileDir *logging.HTTPFileDirectory

	// HTTP method, such as GET.
	method string

	// OAS operation identifier.
	operationId string

	// URL path, such as /path.
	path string
}

// NewGeneratedHandler creates a generated handler via method, path, and handler
// function.
func NewGeneratedHandler(ctx context.Context, httpFileDir *logging.HTTPFileDirectory, method string, path string, operationId string, handlerFunc http.HandlerFunc) *GeneratedHandler {
	return &GeneratedHandler{
		handlerFunc: handlerFunc,
		httpFileDir: httpFileDir,
		method:      method,
		operationId: operationId,
		path:        path,
	}
}

// HandlerFunc returns the underlying HTTP handler function.
func (h GeneratedHandler) HandlerFunc() http.HandlerFunc {
	return h.httpFileDir.HandlerFunc(h.operationId, h.handlerFunc)
}

// HandlerPattern returns the method and path in a [http.ServeMux] compatible
// pattern.
func (h GeneratedHandler) HandlerPattern() string {
	return h.method + " " + h.path
}
