// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"mockserver/internal/handler/assert"
	"net/http"
)

func opLogoutUser() http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		if err := assert.SecurityHeader(req, "api_key", false); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := assert.HeaderValues(req, "Accept", []string{"*/*"}); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := assert.HeaderExists(req, "User-Agent"); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		w.WriteHeader(http.StatusOK)
	}
}
