/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Petstore } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Orders Place Order", async () => {
  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("placeOrder"),
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.orders.place({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});

test("Orders Get Order By Id", async () => {
  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("getOrderById"),
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.orders.getById({
    orderId: 614993,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});

test("Orders Delete Order", async () => {
  const petstore = new Petstore({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: createTestHTTPClient("deleteOrder"),
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.orders.delete({
    orderId: 127902,
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    petId: 198772,
    quantity: 7,
    status: "approved",
  });
});
