/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Petstore } from "../index.js";

test("Pets Update Pet", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.pets.update({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
      "<value>",
    ],
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
    ],
  });
});

test("Pets Add Pet", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.pets.add({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
    ],
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
    ],
  });
});

test("Pets Find Pets By Status", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.pets.findByStatus({});
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual([
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
      ],
    },
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
      ],
    },
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
      ],
    },
  ]);
});

test("Pets Find Pets By Tags", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.pets.findByTags({});
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual([
    {
      id: 10,
      name: "doggie",
      category: {
        id: 1,
        name: "Dogs",
      },
      photoUrls: [
        "<value>",
        "<value>",
        "<value>",
      ],
    },
  ]);
});

test("Pets Get Pet By Id", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.pets.get({
    petId: 504151,
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
    ],
  });
});

test("Pets Delete Pet", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.pets.delete({
    petId: 441876,
  });
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value>",
    ],
  });
});
