/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Petstore } from "../index.js";

test("Stores Get Inventory", async () => {
  const petstore = new Petstore({
    apiKey: process.env["PETSTORE_API_KEY"] ?? "",
  });
  const result = await petstore.stores.getInventory();
  expect(result).toBeDefined();
  expect(result).toBeDefined();
  expect(result).toEqual({
    "key": 373538,
  });
});
