/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersDelete } from "../funcs/ordersDelete.js";
import { ordersGetById } from "../funcs/ordersGetById.js";
import { ordersPlace } from "../funcs/ordersPlace.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Orders extends ClientSDK {
  /**
   * Place an order for a pet
   *
   * @remarks
   * Place a new order in the store
   */
  async place(
    request?: components.Order | undefined,
    options?: RequestOptions,
  ): Promise<components.Order> {
    return unwrapAsync(ordersPlace(
      this,
      request,
      options,
    ));
  }

  /**
   * Find purchase order by ID
   *
   * @remarks
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   */
  async getById(
    request: operations.GetOrderByIdRequest,
    options?: RequestOptions,
  ): Promise<components.Order> {
    return unwrapAsync(ordersGetById(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete purchase order by ID
   *
   * @remarks
   * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
   */
  async delete(
    request: operations.DeleteOrderRequest,
    options?: RequestOptions,
  ): Promise<components.Order> {
    return unwrapAsync(ordersDelete(
      this,
      request,
      options,
    ));
  }
}
