/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Orders } from "./orders.js";
import { Pets } from "./pets.js";
import { Stores } from "./stores.js";
import { Users } from "./users.js";

export class Petstore extends ClientSDK {
  private _pets?: Pets;
  get pets(): Pets {
    return (this._pets ??= new Pets(this._options));
  }

  private _stores?: Stores;
  get stores(): Stores {
    return (this._stores ??= new Stores(this._options));
  }

  private _orders?: Orders;
  get orders(): Orders {
    return (this._orders ??= new Orders(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }
}
