/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storesGetInventory } from "../funcs/storesGetInventory.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Stores extends ClientSDK {
  /**
   * Returns pet inventories by status
   *
   * @remarks
   * Returns a map of status codes to quantities
   */
  async getInventory(
    options?: RequestOptions,
  ): Promise<{ [k: string]: number }> {
    return unwrapAsync(storesGetInventory(
      this,
      options,
    ));
  }
}
